tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
brew "brew-php-switcher"
brew "cask"
brew "composer"
brew "curl", args: ["with-libssh2", "with-openssl"]
brew "git"
brew "httpd", args: ["with-privileged-ports"]
brew "node"
brew "php@5.6", args: ["with-homebrew-curl", "with-httpd24", "without-ldap"]
brew "php@7.0", args: ["with-homebrew-curl", "with-httpd24"]
brew "php@7.1", args: ["with-homebrew-curl", "with-httpd24"]
brew "redis"
brew "ruby", link: false
brew "ssh-copy-id"
brew "thefuck"
brew "virtualhost.sh"
brew "zsh"
cask "gimp"
cask "grandperspective"
cask "the-unarchiver"
cask "alfred"
cask "sequel-pro"
cask "spotify"
cask "transmit"
cask "google-chrome"
cask "iterm2"
cask "postman"
cask "jetbrains-toolbox"
cask "homebrew/cask-fonts/font-awesome-terminal-fonts"
cask "homebrew/cask-fonts/font-fontawesome"
cask "homebrew/cask-fonts/font-hack-nerd-font"
cask "homebrew/cask-fonts/font-source-code-pro"
